import playsound
import termcolor
import time
from pygame import mixer

def victory_screen():

    text = "victorious"
    printString = termcolor.colored(text,'red','on_blue', attrs=['bold'])
    playsound.playsound('Plants Vs Zombies Victory Jingle.mp3')
    print (printString) 
    answer = input()


def Lose():
    gameOverText = "Loser xd"
    printString2 = termcolor.colored(gameOverText,'white', attrs=['bold','blink'])
    playsound.playsound('Regular Show Intro sound effect.mp3')
    print (printString2)
    answer = input()

block = False
mixer.init()
mixer.music.load('Terraria Music - Ocean.mp3')
mixer.music.play()


print ("Welcome to Jabari Jumps: The video game")
time.sleep(2)
print ("once upon a time there was a boy named Jabari")
time.sleep(2)
print ("one day Jabari and his family decided to go to the amusment park together")
time.sleep(2)
print ("at this pool there was a very very tall diving board")
time.sleep(2)
print ("For as long as Jabari could remember he wanted to dive off the tall board, but he could never gather the courage")
time.sleep(2)
print ("today was the day he would jump off of it jabari thought")
time.sleep(2)
print ("on his way towards the diving boards")
time.sleep(2)
print ("He bumped into a bully who scared jabari into not being able to jump of the diving board and then called him a coward.")
time.sleep(2)
print("Jabari had to know defeat his fear and prove the bully wrong.")
time.sleep(2)
print ("You are faced with a descision: do you want to turn back or do you want to continue (type continue or give up)")


answer1 = input('write contnue of give up:')
if answer1 == 'continue':
    print ('The bully shows you 4 challenges, to the north is the diving board, to the east is rock climbing, to the west is a roller coaster, and to the south is a water slide.')
if answer1 == 'give up': 
    Lose()
mixer.music.stop()

answer2 = input('north,west,east, or south?')

if answer2 == 'north':
    mixer.init()
    mixer.music.load('bad piggies drip.mp3')
    mixer.music.play()
    print ("you start making your way over to the diving board")
    time.sleep(2)
    print ("the line to the diving board is long and tests your patience, you get very nervous thinking about jumping off the board")
    time.sleep(2)
    print ("You are now at the base of the diving board looking up, it looks so much taller from here.")
    time.sleep(2)
    print ("you start climbing anyway")
    time.sleep(2)
    print ("As you walk over the water you start to doubt yourself")
    time.sleep(2)
    answerDiving = input('Are you sure you want to do this?!?!(yes or no)')
    if answerDiving == 'yes':
        print("you jump off the board")
        time.sleep(1)
        print("A     ")
        time.sleep(1)
        print(" A")
        time.sleep(1)
        print("  A")
        time.sleep(1)
        print("   A")
        time.sleep(1)
        print("  A")
        time.sleep(1)
        print(" A")
        time.sleep(1)
        print("A")
        time.sleep(1)
        print ("SPLOOSH")
        time.sleep(3)
        print ("WOW you think to yourself, that is one of the most fun things you have ever done the wait and the nervousness was worth it, now that you did it you feel confident in yourself, you might go again in the future.")
        time.sleep(2)
        print("You head back to the main area")
    if answerDiving == 'no':
        Lose()

mixer.music.stop()



if answer2 == 'east':
    mixer.init()
    mixer.music.load('Doom OST - E1M1 - At Dooms Gate.mp3')
    mixer.music.play()
    print("you head east to the rock climbing/ high ropes course")
    time.sleep(2)
    print("the line for this course is very long aswell")
    time.sleep(2)
    print("not only is the wait testing your patience but the course itself looks really hard to finish")
    time.sleep(2)
    print("you get to the base of the course and put on your safety gear, all the ropes and gear make you nervous.")
    time.sleep(2)
    print("it is not so bad when you first start")
    time.sleep(2)
    print("As you climb you palms get sweaty and your muscles start feeling week")
    time.sleep(2)
    print("near the top you decide it is too much and you give up, the person holding your rope on the bottem still ecourages you to keep climbing.")
    answerClimbing = input('do you want to continue climbing?(yes or no)')
    if answerClimbing == 'yes':
        print ("you carry on, despite the fear and the pain on your body")
        time.sleep(2)
        print("you finally make it to the top, the view is beautiful, you ring the bell and the rope slowly let'syou down. This is the greatest relief you have ever felt.")
        time.sleep(2)
        print("you head back to the main area")
        mixer.music.stop()
    if answerClimbing == 'no':
        Lose()


if answer2 == 'west':
    mixer.init()
    mixer.music.load('Loonboon.mp3')
    mixer.music.play()
    print("You make your way over to the roller coaster")
    time.sleep(2)
    print("you look up at all the loopty loops, the height of the coaster and the speed from the line")
    time.sleep(2)
    print("This must easily be the scariest challeng of them all")
    time.sleep(2)
    print("as you get near the cart you see a man get out and throw up, this makes you doubt you descision of going on this ride")
    time.sleep(2)
    answerRide = input("are you sure you want to go on this ride?(yes or no)")
    if answerRide == 'yes':
        print("you board the cart")
        time.sleep(2)
        print("You start to move")
        time.sleep(2)
        print("you go really high up and then drop")
        time.sleep(2)
        print("the loops and the speed is super exciting")
        time.sleep(2)
        print("the ride comes back to the beginning and you wish it could keep going")
        time.sleep(2)
        print("you go back to the main area.")
    if answerRide == 'no':
        Lose()
mixer.music.stop()

if answer2 == 'south':
    mixer.init()
    mixer.music.load('1700s sea shanties.mp3')
    mixer.music.play()
    print("You head to the water slides")
    time.sleep(2)
    print("While waiting in the line to the slide you see that the slide is a tube that seems very tight")
    time.sleep(2)
    print("It is also very long and fast")
    time.sleep(2)
    print("you get to the top of the slide and see other people getting shot down it after a count down")
    time.sleep(2)
    answerSlide = input('are you sure you want to do this(yes or no)')
    if answerSlide == 'yes':
        print("you step into the chute, it feets uncomfortable and tight")
        time.sleep(2)
        print("then the count down begins")
        time.sleep(2)
        print("5")
        time.sleep(1)
        print("4")
        time.sleep(1)
        print("3")
        time.sleep(1)
        print("2")
        time.sleep(1)
        print("1")
        time.sleep(1)
        print("you get shot down the slide at a super fast speed")
        time.sleep(2)
        print("you struggle to keep youself together at first but the speed is very fun")
        time.sleep(2)
        print("you soon get shot out the end of the slide and drop into the pool below SPLOOOOOOSH")
        time.sleep(2)
        print("you head back to the main area")
        time.sleep(2)
    if answerSlide == 'no':
        Lose()

answer3 = input('north,west,east, or south?')

if answer3 == 'north':
    mixer.init()
    mixer.music.load('bad piggies drip.mp3')
    mixer.music.play()
    print ("you start making your way over to the diving board")
    time.sleep(2)
    print ("the line to the diving board is long and tests your patience, you get very nervous thinking about jumping off the board")
    time.sleep(2)
    print ("You are now at the base of the diving board looking up, it looks so much taller from here.")
    time.sleep(2)
    print ("you start climbing anyway")
    time.sleep(2)
    print ("As you walk over the water you start to doubt yourself")
    time.sleep(2)
    answerDiving = input('Are you sure you want to do this?!?!(yes or no)')
    if answerDiving == 'yes':
        print("you jump off the board")
        time.sleep(1)
        print("A     ")
        time.sleep(1)
        print(" A")
        time.sleep(1)
        print("  A")
        time.sleep(1)
        print("   A")
        time.sleep(1)
        print("  A")
        time.sleep(1)
        print(" A")
        time.sleep(1)
        print("A")
        time.sleep(1)
        print ("SPLOOSH")
        time.sleep(3)
        print ("WOW you think to yourself, that is one of the most fun things you have ever done the wait and the nervousness was worth it, now that you did it you feel confident in yourself, you might go again in the future.")
        time.sleep(2)
        print("You head back to the main area")
    if answerDiving == 'no':
        Lose()

mixer.music.stop()



if answer3 == 'east':
    mixer.init()
    mixer.music.load('Doom OST - E1M1 - At Dooms Gate.mp3')
    mixer.music.play()
    print("you head east to the rock climbing/ high ropes course")
    time.sleep(2)
    print("the line for this course is very long aswell")
    time.sleep(2)
    print("not only is the wait testing your patience but the course itself looks really hard to finish")
    time.sleep(2)
    print("you get to the base of the course and put on your safety gear, all the ropes and gear make you nervous.")
    time.sleep(2)
    print("it is not so bad when you first start")
    time.sleep(2)
    print("As you climb you palms get sweaty and your muscles start feeling week")
    time.sleep(2)
    print("near the top you decide it is too much and you give up, the person holding your rope on the bottem still ecourages you to keep climbing.")
    answerClimbing = input('do you want to continue climbing?(yes or no)')
    if answerClimbing == 'yes':
        print ("you carry on, despite the fear and the pain on your body")
        time.sleep(2)
        print("you finally make it to the top, the view is beautiful, you ring the bell and the rope slowly let'syou down. This is the greatest relief you have ever felt.")
        time.sleep(2)
        print("you head back to the main area")
        mixer.music.stop()
    if answerClimbing == 'no':
        Lose()


if answer3 == 'west':
    mixer.init()
    mixer.music.load('Loonboon.mp3')
    mixer.music.play()
    print("You make your way over to the roller coaster")
    time.sleep(2)
    print("you look up at all the loopty loops, the height of the coaster and the speed from the line")
    time.sleep(2)
    print("This must easily be the scariest challeng of them all")
    time.sleep(2)
    print("as you get near the cart you see a man get out and throw up, this makes you doubt you descision of going on this ride")
    time.sleep(2)
    answerRide = input("are you sure you want to go on this ride?(yes or no)")
    if answerRide == 'yes':
        print("you board the cart")
        time.sleep(2)
        print("You start to move")
        time.sleep(2)
        print("you go really high up and then drop")
        time.sleep(2)
        print("the loops and the speed is super exciting")
        time.sleep(2)
        print("the ride comes back to the beginning and you wish it could keep going")
        time.sleep(2)
        print("you go back to the main area.")
    if answerRide == 'no':
        Lose()
mixer.music.stop()

if answer3 == 'south':
    mixer.init()
    mixer.music.load('1700s sea shanties.mp3')
    mixer.music.play()
    print("You head to the water slides")
    time.sleep(2)
    print("While waiting in the line to the slide you see that the slide is a tube that seems very tight")
    time.sleep(2)
    print("It is also very long and fast")
    time.sleep(2)
    print("you get to the top of the slide and see other people getting shot down it after a count down")
    time.sleep(2)
    answerSlide = input('are you sure you want to do this(yes or no)')
    if answerSlide == 'yes':
        print("you step into the chute, it feets uncomfortable and tight")
        time.sleep(2)
        print("then the count down begins")
        time.sleep(2)
        print("5")
        time.sleep(1)
        print("4")
        time.sleep(1)
        print("3")
        time.sleep(1)
        print("2")
        time.sleep(1)
        print("1")
        time.sleep(1)
        print("you get shot down the slide at a super fast speed")
        time.sleep(2)
        print("you struggle to keep youself together at first but the speed is very fun")
        time.sleep(2)
        print("you soon get shot out the end of the slide and drop into the pool below SPLOOOOOOSH")
        time.sleep(2)
        print("you head back to the main area")
        time.sleep(2)
    if answerSlide == 'no':
        Lose()
        
answer4 = input('north,west,east, or south?')

if answer4 == 'north':
    mixer.init()
    mixer.music.load('bad piggies drip.mp3')
    mixer.music.play()
    print ("you start making your way over to the diving board")
    time.sleep(2)
    print ("the line to the diving board is long and tests your patience, you get very nervous thinking about jumping off the board")
    time.sleep(2)
    print ("You are now at the base of the diving board looking up, it looks so much taller from here.")
    time.sleep(2)
    print ("you start climbing anyway")
    time.sleep(2)
    print ("As you walk over the water you start to doubt yourself")
    time.sleep(2)
    answerDiving = input('Are you sure you want to do this?!?!(yes or no)')
    if answerDiving == 'yes':
        print("you jump off the board")
        time.sleep(1)
        print("A     ")
        time.sleep(1)
        print(" A")
        time.sleep(1)
        print("  A")
        time.sleep(1)
        print("   A")
        time.sleep(1)
        print("  A")
        time.sleep(1)
        print(" A")
        time.sleep(1)
        print("A")
        time.sleep(1)
        print ("SPLOOSH")
        time.sleep(3)
        print ("WOW you think to yourself, that is one of the most fun things you have ever done the wait and the nervousness was worth it, now that you did it you feel confident in yourself, you might go again in the future.")
        time.sleep(2)
        print("You head back to the main area")
    if answerDiving == 'no':
        Lose()

mixer.music.stop()



if answer4 == 'east':
    mixer.init()
    mixer.music.load('Doom OST - E1M1 - At Dooms Gate.mp3')
    mixer.music.play()
    print("you head east to the rock climbing/ high ropes course")
    time.sleep(2)
    print("the line for this course is very long aswell")
    time.sleep(2)
    print("not only is the wait testing your patience but the course itself looks really hard to finish")
    time.sleep(2)
    print("you get to the base of the course and put on your safety gear, all the ropes and gear make you nervous.")
    time.sleep(2)
    print("it is not so bad when you first start")
    time.sleep(2)
    print("As you climb you palms get sweaty and your muscles start feeling week")
    time.sleep(2)
    print("near the top you decide it is too much and you give up, the person holding your rope on the bottem still ecourages you to keep climbing.")
    answerClimbing = input('do you want to continue climbing?(yes or no)')
    if answerClimbing == 'yes':
        print ("you carry on, despite the fear and the pain on your body")
        time.sleep(2)
        print("you finally make it to the top, the view is beautiful, you ring the bell and the rope slowly let'syou down. This is the greatest relief you have ever felt.")
        time.sleep(2)
        print("you head back to the main area")
        mixer.music.stop()
    if answerClimbing == 'no':
        Lose()


if answer4 == 'west':
    mixer.init()
    mixer.music.load('Loonboon.mp3')
    mixer.music.play()
    print("You make your way over to the roller coaster")
    time.sleep(2)
    print("you look up at all the loopty loops, the height of the coaster and the speed from the line")
    time.sleep(2)
    print("This must easily be the scariest challeng of them all")
    time.sleep(2)
    print("as you get near the cart you see a man get out and throw up, this makes you doubt you descision of going on this ride")
    time.sleep(2)
    answerRide = input("are you sure you want to go on this ride?(yes or no)")
    if answerRide == 'yes':
        print("you board the cart")
        time.sleep(2)
        print("You start to move")
        time.sleep(2)
        print("you go really high up and then drop")
        time.sleep(2)
        print("the loops and the speed is super exciting")
        time.sleep(2)
        print("the ride comes back to the beginning and you wish it could keep going")
        time.sleep(2)
        print("you go back to the main area.")
    if answerRide == 'no':
        Lose()
mixer.music.stop()

if answer4 == 'south':
    mixer.init()
    mixer.music.load('1700s sea shanties.mp3')
    mixer.music.play()
    print("You head to the water slides")
    time.sleep(2)
    print("While waiting in the line to the slide you see that the slide is a tube that seems very tight")
    time.sleep(2)
    print("It is also very long and fast")
    time.sleep(2)
    print("you get to the top of the slide and see other people getting shot down it after a count down")
    time.sleep(2)
    answerSlide = input('are you sure you want to do this(yes or no)')
    if answerSlide == 'yes':
        print("you step into the chute, it feets uncomfortable and tight")
        time.sleep(2)
        print("then the count down begins")
        time.sleep(2)
        print("5")
        time.sleep(1)
        print("4")
        time.sleep(1)
        print("3")
        time.sleep(1)
        print("2")
        time.sleep(1)
        print("1")
        time.sleep(1)
        print("you get shot down the slide at a super fast speed")
        time.sleep(2)
        print("you struggle to keep youself together at first but the speed is very fun")
        time.sleep(2)
        print("you soon get shot out the end of the slide and drop into the pool below SPLOOOOOOSH")
        time.sleep(2)
        print("you head back to the main area")
        time.sleep(2)
    if answerSlide == 'no':
        Lose()
answer5 = input('north,west,east, or south?')

if answer5 == 'north':
    mixer.init()
    mixer.music.load('bad piggies drip.mp3')
    mixer.music.play()
    print ("you start making your way over to the diving board")
    time.sleep(2)
    print ("the line to the diving board is long and tests your patience, you get very nervous thinking about jumping off the board")
    time.sleep(2)
    print ("You are now at the base of the diving board looking up, it looks so much taller from here.")
    time.sleep(2)
    print ("you start climbing anyway")
    time.sleep(2)
    print ("As you walk over the water you start to doubt yourself")
    time.sleep(2)
    answerDiving = input('Are you sure you want to do this?!?!(yes or no)')
    if answerDiving == 'yes':
        print("you jump off the board")
        time.sleep(1)
        print("A     ")
        time.sleep(1)
        print(" A")
        time.sleep(1)
        print("  A")
        time.sleep(1)
        print("   A")
        time.sleep(1)
        print("  A")
        time.sleep(1)
        print(" A")
        time.sleep(1)
        print("A")
        time.sleep(1)
        print ("SPLOOSH")
        time.sleep(3)
        print ("WOW you think to yourself, that is one of the most fun things you have ever done the wait and the nervousness was worth it, now that you did it you feel confident in yourself, you might go again in the future.")
        time.sleep(2)
        print("You head back to the main area")
    if answerDiving == 'no':
        Lose()

mixer.music.stop()



if answer5 == 'east':
    mixer.init()
    mixer.music.load('Doom OST - E1M1 - At Dooms Gate.mp3')
    mixer.music.play()
    print("you head east to the rock climbing/ high ropes course")
    time.sleep(2)
    print("the line for this course is very long aswell")
    time.sleep(2)
    print("not only is the wait testing your patience but the course itself looks really hard to finish")
    time.sleep(2)
    print("you get to the base of the course and put on your safety gear, all the ropes and gear make you nervous.")
    time.sleep(2)
    print("it is not so bad when you first start")
    time.sleep(2)
    print("As you climb you palms get sweaty and your muscles start feeling week")
    time.sleep(2)
    print("near the top you decide it is too much and you give up, the person holding your rope on the bottem still ecourages you to keep climbing.")
    answerClimbing = input('do you want to continue climbing?(yes or no)')
    if answerClimbing == 'yes':
        print ("you carry on, despite the fear and the pain on your body")
        time.sleep(2)
        print("you finally make it to the top, the view is beautiful, you ring the bell and the rope slowly let'syou down. This is the greatest relief you have ever felt.")
        time.sleep(2)
        print("you head back to the main area")
        mixer.music.stop()
    if answerClimbing == 'no':
        Lose()


if answer5 == 'west':
    mixer.init()
    mixer.music.load('Loonboon.mp3')
    mixer.music.play()
    print("You make your way over to the roller coaster")
    time.sleep(2)
    print("you look up at all the loopty loops, the height of the coaster and the speed from the line")
    time.sleep(2)
    print("This must easily be the scariest challeng of them all")
    time.sleep(2)
    print("as you get near the cart you see a man get out and throw up, this makes you doubt you descision of going on this ride")
    time.sleep(2)
    answerRide = input("are you sure you want to go on this ride?(yes or no)")
    if answerRide == 'yes':
        print("you board the cart")
        time.sleep(2)
        print("You start to move")
        time.sleep(2)
        print("you go really high up and then drop")
        time.sleep(2)
        print("the loops and the speed is super exciting")
        time.sleep(2)
        print("the ride comes back to the beginning and you wish it could keep going")
        time.sleep(2)
        print("you go back to the main area.")
    if answerRide == 'no':
        Lose()
mixer.music.stop()

if answer5 == 'south':
    mixer.init()
    mixer.music.load('1700s sea shanties.mp3')
    mixer.music.play()
    print("You head to the water slides")
    time.sleep(2)
    print("While waiting in the line to the slide you see that the slide is a tube that seems very tight")
    time.sleep(2)
    print("It is also very long and fast")
    time.sleep(2)
    print("you get to the top of the slide and see other people getting shot down it after a count down")
    time.sleep(2)
    answerSlide = input('are you sure you want to do this(yes or no)')
    if answerSlide == 'yes':
        print("you step into the chute, it feets uncomfortable and tight")
        time.sleep(2)
        print("then the count down begins")
        time.sleep(2)
        print("5")
        time.sleep(1)
        print("4")
        time.sleep(1)
        print("3")
        time.sleep(1)
        print("2")
        time.sleep(1)
        print("1")
        time.sleep(1)
        print("you get shot down the slide at a super fast speed")
        time.sleep(2)
        print("you struggle to keep youself together at first but the speed is very fun")
        time.sleep(2)
        print("you soon get shot out the end of the slide and drop into the pool below SPLOOOOOOSH")
        time.sleep(2)
        print("you head back to the main area")
        time.sleep(2)
    if answerSlide == 'no':
        Lose()

print ("you go home happy, the bully leaves you alone, and learn to take calculated risks") 
victory_screen()
